global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ckb-mainnet'
    static_configs:
      - targets: ['mainnet-node-1:8090', 'mainnet-node-2:8090']

  - job_name: 'ckb-testnet'
    static_configs:
      - targets: ['testnet-node-1:8090']
